before:
  hooks:
    - go mod download
builds:
- id: "pslive"
  main: ./cmd/pslive
  binary: pslive
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
- id: "pslocal"
  main: ./cmd/pslocal
  binary: pslocal
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm
  goarm:
    - 7
archives:
  - id: "pslive"
    builds: ["pslive"]
    name_template: "pslive_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
  - id: "pslocal"
    builds: ["pslocal"]
    name_template: "pslocal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
  prerelease: auto
dockers:
  -
    id: pslive
    ids:
      - pslive
    dockerfile: "Dockerfile.pslive"
    image_templates:
    - "ghcr.io/sargassum-world/pslive:latest"
    - "ghcr.io/sargassum-world/pslive:{{ .Major }}"
    - "ghcr.io/sargassum-world/pslive:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/sargassum-world/pslive:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
  -
    id: pslocal
    ids:
      - pslocal
    dockerfile: "Dockerfile.pslocal"
    image_templates:
    - "ghcr.io/sargassum-world/pslocal:latest"
    - "ghcr.io/sargassum-world/pslocal:{{ .Major }}"
    - "ghcr.io/sargassum-world/pslocal:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/sargassum-world/pslocal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
